### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by angelxmoreno** [t3chnoboy/amazon-product-api#11]
Is there any solution in place for caching requests?

**Comment by t3chnoboy** [comment]
Sorry for the late response.
We are using https://github.com/request/request for http requests. It does not support caching.

**Comment by angelxmoreno** [comment]
OK, Thank you. I'll create a wrapper to check a datasource prior to making a direct call. Thanks for the reply.

**Comment by jurgob** [comment]
I know that it is closed, but I really think that a caching system would be really helpfull!

**Comment by masterT** [comment]
I use [Redis](http://redis.io/) to cache my responses, because I use this module in a web context.
