### ISSUE TITLE
I have some issue in a React /Gatsby app

### ISSUE THREAD

**Issue by arhoy** [t3chnoboy/amazon-product-api#119]
I have the following error which I cannot figure out

> Can't resolve 'tls' in 'C:\Users\arhoy\Desktop\web development\production\ripplejs.com\node_modules\tunnel-agent'

Any suggestions?

**Comment by arhoy** [comment]
Basically it fails and shows error 

Can't resolve 'net' in 'C:\Users\arhoy\Desktop\web\node_modules\tunnel-agent'
Can't resolve 'net' in 'C:\Users\arhoy\Desktop\web\node_modules\tough-cookie\lib'
Can't resolve 'net' in 'C:\Users\arhoy\Desktop\web\node_modules\forever-agent'

When I try to import it

**Comment by JuanCrg90** [comment]
that are dependencies for nodejs this package is for backend usage that is the reason of the error.

#66 #86
