### ISSUE TITLE
Can't search for a specify artist

### ISSUE THREAD

**Issue by masterT** [t3chnoboy/amazon-product-api#16]
Can only search by keyword.

**Comment by JuanCrg90** [comment]
Hi, can you lend me a snippet of your query?

**Comment by masterT** [comment]
What I would like to do *ItemSearch* like that:
```JS
client.itemSearch({
  artist: 'Muse',
  condition: 'All',
  searchIndex: Music
}, callback);
```

But the artist param is not supported, but there also a lot of param that are not supported if you check  in the [documentation](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemSearch.html).

**Comment by masterT** [comment]
I'm gonna code it and make a pull request.
