### ISSUE TITLE
ItemLookUp fails if the itemTypeId is ASIN and the default param SearchIndex is present

### ISSUE THREAD

**Issue by Codepoet77** [t3chnoboy/amazon-product-api#24]
The response from Amazon states that SearchIndex cannot be present when searching by ASIN. I am about to submit a fix for this.

**Comment by Codepoet77** [comment]
PR has been submitted for this issue.

**Comment by masterT** [comment]
@Codepoet77 I merged your pull request, but the tests failed. I Fixed it and now I will publish it!

**Comment by masterT** [comment]
Now version 0.3.4
