### ISSUE TITLE
Question: Any reason not to use the latest version of the API?

### ISSUE THREAD

**Issue by FdezRomero** [t3chnoboy/amazon-product-api#26]
Hi guys,

Out of curiosity, I just wanted to know if there is any reason not to use the latest version of the Amazon Product Advertising API (2013-08-01). Are there any differences or performance related? Maybe for compatibility/legacy support?

Thanks!

**Comment by masterT** [comment]
That is a good question @t3chnoboy

**Comment by kauegimenes** [comment]
Here is some info from the API docs: http://docs.aws.amazon.com/AWSECommerceService/latest/DG/CommonRequestParameters.html

``````
The version of the Product Advertising API software and WSDL to use. By default, the 2011-08-01 version is used. Alternately, specify a software version, such as 2013-08-01. For a list of valid version numbers, refer to the Product Advertising API Release Notes. Note that the latest version of Product Advertising API is not used by default.
Default: 2011-08-01

Valid values: Valid WSDL version date, for example, 2013-08-01.
`````

**Comment by t3chnoboy** [comment]
afaik, the version we use (2013-08-01) is the latest

**Comment by FdezRomero** [comment]
@t3chnoboy For `ItemLookup` it seems to be using `2011-08-01`: https://github.com/t3chnoboy/amazon-product-api/blob/master/lib/utils.js#L73

**Comment by t3chnoboy** [comment]
@FdezRomero hmmm Can you try changing it to the latest version and make sure all tests are passing?

**Comment by FdezRomero** [comment]
I'll try some time this week @t3chnoboy. Not that I found a need or something not working as expected, I was just curious about using a different API version for this operation.

**Comment by FdezRomero** [comment]
Finally I found the time to test changing the API version to 2013-08-01 and everything is working as expected. I also noticed a tiny speed improvement when many variants are returned, but might be unrelated.

Sent PR #35 with the change.

**Comment by masterT** [comment]
@t3chnoboy can we close this issue?
