### ISSUE TITLE
Setting locale

### ISSUE THREAD

**Issue by brycemolder** [t3chnoboy/amazon-product-api#32]
I didn't see instructions on how to set the Locale.  Can I do:

        var client = AmazonShopping.createClient({
            awsId: "AKIAIZWLasdfasdfasdfasdfd",
            awsSecret: "yzOAltW4asdfasdfasdf",
            awsTag: "xxxxxxx",
            locale : "Mexico"
        });

**Comment by adamrogas** [comment]
The Product Advertising API is available in the following locales:

Locale	URL

Brazil	
http://webservices.amazon.com.br

Canada	
http://webservices.amazon.ca

China	
http://webservices.amazon.cn

France	
http://webservices.amazon.fr

Germany	
http://webservices.amazon.de

India	
http://webservices.amazon.in/

Italy	
http://webservices.amazon.it

Japan	
http://webservices.amazon.co.jp

Mexico	
http://webservices.amazon.com.mx

Spain	
http://webservices.amazon.es

United Kingdom	
http://webservices.amazon.co.uk/

United States	
http://webservices.amazon.com

So this would probably work: 

client.itemLookup({

      browseNodeId: '549726',
      responseGroup: 'NewReleases',
      domain: 'webservices.amazon.com.mx'

    }, function (err, results) {
      if (err) {
        console.log(err);
      } else {
        console.log(results);
      }

**Comment by sreeraghuparuchuri** [comment]
Hi @brycemolder  @adamrogas 
 
I am working on similar lines.. can you guys confirm if this worked?

**Comment by sreeraghuparuchuri** [comment]
Update : I tried and it worked.
domain: '<required domain>'

**Comment by jaribu** [comment]
Hi,
I tried this code and I get : [ { Error: [ [Object], [Object] ] } ]
`client.itemLookup({

  browseNodeId: '549726',
  responseGroup: 'NewReleases',
  domain: 'webservices.amazon.com.mx'

}, function (err, results) {
  if (err) {
    console.log(err);
  } else {
    console.log(results);
  }
});`

Can you explain can you explain me how to do this ?

**Comment by masterT** [comment]
Hi there,

To use a different endpoint in your request, you need the choose it from the [Endpoints list](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/AnatomyOfaRESTRequest.html#EndpointsandWebServices). Then pass the **domain** of the endpoint in the **domain** params of your query.

Example:

I want to query the Canadian store 🇨🇦 . 
The endpoint is **https://webservices.amazon.ca/onca/xml**.
The **domain** of the endpoint is **webservices.amazon.ca**.


```js
var query = {
  artist: 'Radiohead',
  searchIndex: 'Music',
  sort: 'relevancerank',
  itemPage: 1,
  availability: 'Available',
  responseGroup: 'OfferFull,Large,Images',
  domain: 'webservices.amazon.ca'
};
client.itemSearch(query, function (error, results) {
  if (error) {
    console.log(error);
  } else {
    console.log(results);
  }
})
```

**Comment by masterT** [comment]
@jaribu maybe the error is not a domain problem. Can you log the error message?

**Comment by masterT** [comment]
Add how to specify the endpoint in the [README.md](https://github.com/t3chnoboy/amazon-product-api/blob/master/README.md#specify-the-endpoint).
