### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by christian4423** [t3chnoboy/amazon-product-api#34]
Less of an issue but more of a question. Is there a way to set the number of results you want?

**Comment by masterT** [comment]
Maybe the param **ItemPage** is what you are looking for. It's for the [ItemSearch](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemSearch.html) method.

From the [documentation](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemSearch.html).

> ItemPage
> Retrieves a specific page of items from all of the items in a response. Up to ten items are returned on a page unless Condition equals "All". In that case, ItemSearch returns additional offers for those items, one offer per condition type (if an offer exists)—for example, one new, one used, one refurbished, and one collectible item. Or, for example, if there are no collectible or refurbished offers, ItemSearch returns one new and one used offer. If you do not include ItemPage in your request, the first page is returned. The total number of pages of items found is returned in the TotalPages response tag.

> Valid Values: 1 to 10 (1 to 5 when the search index = "All")

> Type: String

> Default: None

**Comment by christian4423** [comment]
Okay cool. I got that working. Is there anyway to get more than 10 results per request?

**Comment by m-lautenbach** [comment]
Not from the Amazon API, but you could write a method running multiple requests.
