### ISSUE TITLE
Cart operations?

### ISSUE THREAD

**Issue by donovanh** [t3chnoboy/amazon-product-api#36]
<img width="495" alt="screen shot 2016-01-13 at 21 50 17" src="https://cloud.githubusercontent.com/assets/853536/12308942/fc8f6d5c-ba3f-11e5-97ea-3bc3c349853c.png">
Looking into the code, it looks like the itemSearch, Lookup and BrowseNode lookup operations are mapped but other operations such as CartCreate and the cart operations aren't. Is there a way to use this library and use operations like these? Apologies if I'm missing something.

**Comment by masterT** [comment]
Hi,

The cart operations are not implemented yet... but feel free to fork the library and implement the missing operations you need. The library is very simple and new operations can be add easily. 

If you are having trouble don't hesitate. ☺️

But it would be great to plan to implement all the missing operations available.

**Comment by donovanh** [comment]
Good call, I'll have a look and see what I can do :dancer:
