### ISSUE TITLE
Incorrect pricing for item lookup.

### ISSUE THREAD

**Issue by oscarmorrison** [t3chnoboy/amazon-product-api#46]
Example: http://www.amazon.com/gp/offer-listing/1935703013/ref=olp_f_freeShipping?ie=UTF8&f_new=true

Best price is $7.45 including delivery. 

amazon-product-api is return       "Amount": [ "580"
e.g $5.80 which then has $4 shipping when you goto the url.

```
client.itemLookup({
  idType: 'ISBN',
  itemId: '1935703013',
  condition: 'New',
  responseGroup: 'OfferFull'
```

**Comment by masterT** [comment]
This is weird, when I search the product by ISBN on amazon.com I got this result:
![screen shot 2016-03-22 at 08 29 38](https://cloud.githubusercontent.com/assets/2584158/13951580/564117bc-f008-11e5-8d25-c86962922ab7.png)


But when I clicked on the result, I got a different offers:
![screen shot 2016-03-22 at 08 29 57](https://cloud.githubusercontent.com/assets/2584158/13951578/525b47f8-f008-11e5-8178-964efed8f8df.png)

I think that Amazon display the *Prime* over the *New* offer in the search results, but display the real lowest *New* price on the product page.

**Comment by oscarmorrison** [comment]
Yes. But do you know how to get this price. 
I just want the total cheapest price (including postage)

**Comment by masterT** [comment]
The price will not include the shipping rates, probably because it depends on where you are. You can find information about the shipping rates in the here:
http://www.amazon.com/gp/help/customer/display.html?nodeId=468520
