### ISSUE TITLE
Is there anyway to query the UK amazon site?

### ISSUE THREAD

**Issue by ollybritton** [t3chnoboy/amazon-product-api#55]
I'm making a service which will take eBooks from amazon and post them to facebook, which needs to be accessing the UK version of amazon. It appears that there is no way to use UK browseNodes. When I try and use one, it returns:
`[ { Error: [ [Object] ] } ]`.
I've tried changing the `webservices.amazon.com` to `webservices.amazon.co.uk`, but no luck.

Plz help.
![Cat Gif](https://media.giphy.com/media/ciZYL6PAuysz6/giphy.gif)

**Comment by t3chnoboy** [comment]
Hi @ollybritton 
Take a look at this issue https://github.com/t3chnoboy/amazon-product-api/issues/32

**Comment by t3chnoboy** [comment]
@ollybritton can you set `env` variables and run the tests locally?
there's a test for uk domain https://github.com/t3chnoboy/amazon-product-api/blob/master/test/test.coffee#L105-Lundefined
I can't test at this moment because of the problems with my aws account and CI fails because of the same reason.

**Comment by masterT** [comment]
@t3chnoboy should we add a section in the `README.md` on how to use *custom domain*?

**Comment by ollybritton** [comment]
@t3chnoboy @masterT Why don't you create a wiki which describes in more detail how to use the package. It would be useful for n00b1es, like me.

**Comment by masterT** [comment]
All the information to use the module is specified in the [README.md](https://github.com/t3chnoboy/amazon-product-api/blob/master/README.md). There is also a section about how to use a [specific endpoint (domain)](https://github.com/t3chnoboy/amazon-product-api/blob/master/README.md#specify-the-endpoint).
