### ISSUE TITLE
Support for Merchant ID?

### ISSUE THREAD

**Issue by KingScooty** [t3chnoboy/amazon-product-api#6]
Can we get support for the Merchant ID for itemLookup?

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemLookup.html

**Comment by t3chnoboy** [comment]
Yup, that would be great.

**Comment by d1b1** [comment]
Just ran into this. Got a signing issue when a tried to force it into the query.

**Comment by masterT** [comment]
This is fixed since version 0.3.0. You can use all the param available for the methods, which includes the **MerchantId**.
