### ISSUE TITLE
Use fixtures and mock the API calls during in test

### ISSUE THREAD

**Issue by masterT** [t3chnoboy/amazon-product-api#60]

**Comment by masterT** [comment]
I will do this before the end of October.

**Comment by masterT** [comment]
Ok, maybe before the end of November, I saw kinda in the juice at school 💻  🏫 🎒 ✏️ 📚 .

**Comment by masterT** [comment]
I already tried to do it using the [nock](https://github.com/node-nock/nock) module.
PR coming **this weekend**! 😃

**Comment by t3chnoboy** [comment]
Sweet!

**Comment by t3chnoboy** [comment]
Tests are failing because my AWS account has been suspended 🙊

**Comment by masterT** [comment]
Check PR #74 !

**Comment by t3chnoboy** [comment]
@masterT I created the 1.0 milestone.
https://github.com/t3chnoboy/amazon-product-api/milestone/1

**Comment by t3chnoboy** [comment]
Can we close this issue?

**Comment by masterT** [comment]
Yes!
