### ISSUE TITLE
itemPage Restriction

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [t3chnoboy/amazon-product-api#65]
Is there any way to get all the products from amazon with out any restrictions like 10 pages.

**Comment by masterT** [comment]
Not that I know (using the API).

**Comment by joshwcomeau** [comment]
Mhmm, I was just looking through the API docs and it looks like 10 is a fixed rule. 

The solution would be to make several requests in parallel, using `itemPage`. You should be able to get up to 100 results that way, although you'd likely want to ensure that they're loaded as they come in, and not wait for all requests to resolve.

See http://docs.aws.amazon.com/AWSECommerceService/latest/DG/PagingThroughResults.html
