### ISSUE TITLE
Anyway to verify amazon coupon code?

### ISSUE THREAD

**Issue by Nisthar** [t3chnoboy/amazon-product-api#70]
Does this library support checking amazon coupon code?

**Comment by t3chnoboy** [comment]
Hi @Nisthar! Sorry for the late response 😞 
Did you find it in the API docs? https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html

**Comment by Nisthar** [comment]
@t3chnoboy Can't find it in the api docs.

**Comment by t3chnoboy** [comment]
Sorry, I couldn't find it either 😕 
Can you try contacting Amazon support?

**Comment by Nisthar** [comment]
@t3chnoboy Thanks for searching for me. I think they don't have an API for it.
Anyway, I'll contact amazon support :+1:

**Comment by masterT** [comment]
@Nisthar may you can do a [web scraper](https://en.wikipedia.org/wiki/Web_scraping).

**Comment by Nisthar** [comment]
@masterT @t3chnoboy Thanks. Yes, I am now using nightmarejs to do it.
