### ISSUE TITLE
Use syntax linter

### ISSUE THREAD

**Issue by masterT** [t3chnoboy/amazon-product-api#77]
Maybe [JavaScript Standard Style](http://standardjs.com/rules.html)?

**Comment by t3chnoboy** [comment]
Meh, I don't have any preferences.
But the airbnb one has much more stars 😝 

https://github.com/airbnb/javascript - 46k
https://github.com/feross/standard - 9k

**Comment by masterT** [comment]
But it's less sexy! 😢

**Comment by t3chnoboy** [comment]
@masterT Good point. 
![giphy-2](https://cloud.githubusercontent.com/assets/2552790/22473388/cbf39406-e7e9-11e6-9248-f04da2923b1c.gif)

**Comment by t3chnoboy** [comment]
Let's do a ghetto poll: 
Add 👍 to the option that you prefer
@masterT @JuanCrg90 @socketwiz

**Comment by t3chnoboy** [comment]
1. Sexy JavaScript Standard Style
https://github.com/feross/standard

**Comment by t3chnoboy** [comment]
2. Arguably less sexy but definitely more popular Airbnb style guide
https://github.com/airbnb/javascript

**Comment by JuanCrg90** [comment]
I prefer the Airbnb style, i like the semicolons hehe. we could use the ES5 Styleguide https://github.com/airbnb/javascript/tree/es5-deprecated/es5

Also we could add the editorconfig file http://editorconfig.org/

**Comment by masterT** [comment]
For everalone :(

**Comment by JuanCrg90** [comment]
Could we close this issue?

**Comment by masterT** [comment]
Added in PR #90.
