### ISSUE TITLE
sync response

### ISSUE THREAD

**Issue by akelmj** [t3chnoboy/amazon-product-api#79]
when i call this function i get: **undefined**

for example:

```js
var r = amazonGetItem('B002SSUQFG');

function amazonGetItem(asin) {
    var result;
    client.itemLookup({
        idType: 'ASIN',
        itemId: asin
    }).then(function (results) {
        result = results;
    }).catch(function (err) {
        console.log(err);
      result = '';
    });
    return result;
}
```

i want to wait untill the **temLookup** return data?

thanks.

**Comment by masterT** [comment]
Yes, because you return the `result` value before it was assigned in the [Promise](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise).

**Comment by masterT** [comment]
There is **a lot** of asynchronous computations in javascript and nodejs. I recommend you to get familiar with it!

**Comment by akelmj** [comment]
thanks.
