### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 758): UnableToResolveError: Unable to resolve module crypto

### ISSUE THREAD

**Issue by slender9168** [t3chnoboy/amazon-product-api#81]
Hello,
after i installed & imported the package, react-native can't compile any more, here is the error

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 758): UnableToResolveError: Unable to resolve module crypto from C:\bitbucket apps\2017\myApp\node_modules\amazon-product-api\lib\utils.js: Module does not exist in the module map or in these directories:
  C:\bitbucket apps\2017\myApp\node_modules\amazon-product-api\node_modules
,   C:\bitbucket apps\2017\myApp\node_modules

**Comment by ChrizzDF** [comment]
Hi @slender9168,

did you close this issue because you found a solution?
I'M also facing this error right now, so I'm very interested in your findings :)

**Comment by tungbt-2-3-1994** [comment]
Hello @slender9168,
Did you find the solution for this problem?
I'm also encountering the same, please share it.
Thank you!

**Comment by slender9168** [comment]
Hi there,
I have not used react native in a long time & unfortunately I can't remember how I solved this issue.
Hope you're able to solve it.
