### ISSUE TITLE
AWS-tag

### ISSUE THREAD

**Issue by anandg112** [t3chnoboy/amazon-product-api#84]
Hello there,
What is the awsTag in amazon.createClient function? I have the access key ID and secret access key from product advertising API. If you can help, I will appreciate it.

Thanks,
Anand

**Comment by JuanCrg90** [comment]
Hi @anandg112 You can learn more about the Associate Tag in this link.

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/AssociateTag.html
